# Generated by Django 2.2.6 on 2019-10-18 01:00

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dogs', '0003_auto_20191017_2159'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DogPost',
            new_name='ServicePost',
        ),
    ]
